### ISSUE TITLE
[TOMEM-10] 建议创建镜像文档

### ISSUE THREAD

**Issue by inannan423** [le0zh0u/ToMemo-doc#15]
<p>https://tomemo.top/ 在国内服务器打不开，建议使用 Netlify 部署镜像站（使用 .netlify.app) 域名，服务不会使用梯子的用户，此外，建议把文档地址放到 APP 中</p>

**Comment by le0zh0u** [comment]
感谢建议，抱歉这么久才处理。
我已经使用Cloudflare做CDN服务商，来确保国内访问。也会持续寻找合适的方式。
关于文档地址已经添加到了APP中，在设置页面的底部可以看到。

**Comment by inannan423** [comment]
非常感谢！
