### ISSUE TITLE
键盘高度：建议作者把默认值改成当前键盘高度

### ISSUE THREAD

**Issue by dzxcvp** [le0zh0u/ToMemo-doc#2]
希望在app代码里把默认高度改成当前键盘（iOS原生键盘）的高度，这样在切换的时候是不是就不会glitch一下了？第三方键盘体验不好的通病之一就是会跳那么一下。好像一个bug一样。如果在代码层面把app的默认高度都改成适应不同型号不同屏幕大小的iOS原生键盘高度，对不希望看到glitch的用户就会非常友好，至于想调高键盘的用户，视觉上总归是要glitch一下的，影响不大。

**Comment by le0zh0u** [comment]
你好，感谢反馈。现在的设置中有调整键盘高度的功能。
https://tomemo.top/guide/keyboard-settings.html#%E9%94%AE%E7%9B%98%E9%AB%98%E5%BA%A6
这里有设置的演示视频可以看下。核心是可以根据你其他输入法的高度自动调整的。
